# Configuration for probot-no-response - https://github.com/probot/no-response

# Number of days of inactivity before an Issue is closed for lack of response
daysUntilClose: 7
# Label requiring a response
  
  
  For more information on bots in this reporsitory, read [this discussion](https://github.com/wix/Detox/issues/1305).
