#!/usr/bin/env node

const fs = require('fs');

const DETOX_REGEXP = /^DETOX_(?!DISABLE_POD_INSTALL|DISABLE_POSTINSTALL)/;

function main() {
    const [, ...argv] = process.argv;
    const env = Object.keys(process.env)
        .filter(k => DETOX_REGEXP.test(k.toUpperCase()))
        .reduce((acc, key) => {
            acc[key] = process.env[key];
            return acc;
        }, {});

    setTimeout(main, +process.env.CLI_SLEEP);
} else {
    main();
}
