  - wait
  - label: ":ios: Package iOS"
    key: 'ios_package'
    command:
      - "nvm install"
      - "npm run package:ios"
    artifact_paths: "/Users/builder/work/detox/*.tbz"

  - label: ":android: Package android"
    key: 'android_package'
    command:
      - "nvm install"
      - "npm install"
      - "npm run package:android"
    env:
