name: I Need Help with Detox
description: Ask a general how-to question
labels: ["user: need help"]
body:
  - type: markdown
      description: A clear and concise description of what you need help with.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Your environment
      description: "Note: the test runner is set in your detox configuration file (e.g. package.json, detox.config)."
      value: "Detox version:
      \nReact Native version:
      \nNode version:
      \nDevice model:
      \nOS:
      \nTest-runner (select one): jest / other"
