require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

def shared_pods
  config = use_native_modules!

    if !ENV["REACT_NATIVE_VERSION"] || ENV["REACT_NATIVE_VERSION"].match(/0.(68|69|70).*/)
      # Flags change depending on the env values.
      flags = get_default_flags()

      use_react_native!(
        :path => config[:reactNativePath],
        :hermes_enabled => flags[:hermes_enabled],
        :fabric_enabled => flags[:fabric_enabled],
        # :flipper_configuration => FlipperConfiguration.enabled,
        # An absolute path to your application root.
        :app_path => "#{Pod::Config.instance.installation_root}/.."
      )
    else
      use_react_native!(
        # To enable hermes on iOS, change `false` to `true` and then install pods
        :hermes_enabled => false,
  # See https://github.com/wix/Detox/pull/3035#discussion_r774747705
  if !ENV["REACT_NATIVE_VERSION"] || ENV["REACT_NATIVE_VERSION"].match(/0.(66|67|68|69|70).*/)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
